### ISSUE TITLE
README.md - Docker Usage/Notes section unclear

### ISSUE THREAD

**Issue by alvarovillena** [RobotnikAutomation/rb_theron_sim#8]
The "Notes" section under "Docker Usage" shows twice, and it looks like the first one is wrong.

**Comment by alvarovillena** [comment]
@ggari-robotnik Please take a look at this.

**Comment by ggari-robotnik** [comment]
@alvarovillena I improved the documentation on #9 could you check it out?

**Comment by alvarovillena** [comment]
It still looks a bit confusing, doesn't it?
It states that _In order to exit you have to 2 options:_ , but they are not listed immediately. You have the two options at the end, but it is repeated twice with a different second step.

It also says _if you want to enter on the container use the following command in another terminal_, but it does not specify the command

**Comment by ggari-robotnik** [comment]
@alvarovillena Please check the updates according to your comments on #9 

Could you use this template of the README.md  as a minimum for all the robotnik repostiories?

**Comment by alvarovillena** [comment]
This still shows twice: _In order to exit you have to 2 options:_

It looks quite complete and I agree we should use either this or a similar template for all repos. rcomponent package creator also creates a readme template, but unfortunately we tend not to fill it. I'm wondering if we should automate at least the topics/services/params sections to make it easier and less time consuming.
Also, we should enforce the readme creation somehow. For some repos, we could automate an issue that randomly assigns a reviewer to check if the readme is complete and valid, but it will not work for all kind of repos.

**Comment by ggari-robotnik** [comment]
@alvarovillena Done
